config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root 'root#top'
  get 'about/show'
	resources :books
	resources :users, only:[:show, :edit, :update, :index]
  get "/home/about" => 'about#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	validates :title, presence: true
	validates :body, presence: true
	belongs_to :user
	 validates :body, presence: true, uniqueness: true, length: {maximum: 199}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :books, dependent: :destroy
  attachment :profile_image
  validates :name, presence: true, length: {minimum: 2,maximum: 20}
  validates :introduction,length: {maximum: 50}

  #登録時にメールアドレスを不要とする
  def email_required?
    false
  end

  def email_changed?
    false
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def show
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
	before_action :configure_permitted_parameters, if: :devise_controller?
	def after_sign_in_path_for(resource)
		user_path(current_user)
	end
  def after_sign_out_path_for(resource)
    root_path
  end

	
 
  protected
  # def configure_permitted_parameters
    # devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  # end
  def configure_permitted_parameters
    #strong parametersを設定し、usernameを許可
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
   devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  
  end

	
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  def show
    
  	@booker = Book.find(params[:id])
  	@book = Book.new
    @user = User.find(@booker.user_id)

  end

  def index
    @user = User.find(current_user.id)
    @book = Book.new
    @books = Book.page(params[:page]).reverse_order
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user != current_user
    redirect_to books_path
    end  
  	
  end

  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
  		redirect_to book_path, notice:"successfully"
    else
      flash[:notice] = "error"
      render :edit
  	end
  end

  def create
  	@book = Book.new(book_params)

    @book.user_id = current_user.id
  	if @book.save
  		redirect_to book_path(@book.id), notice: "successfully"
    else
      flash[:notice] = "error"
      @books = Book.page(params[:page]).reverse_order
      @user = User.find(current_user.id)
      
     
      render :index

  	end
  end

  def destroy
  	book = Book.find(params[:id])
  	book.destroy
  	redirect_to books_path
  end

  private 
  def book_params
  	params.require(:book).permit(:title, :body)
  end 

end

app/controllers/root_controller.rb
class RootController < ApplicationController
	def top
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
  def show
  	@user = User.find(params[:id])
    @post_images = @user.books.page(params[:page]).reverse_order
  	@book = Book.new
  end
  def index
    @book = Book.new
    @user = User.find(current_user.id)
    @users = User.all

  end

  def edit
  	@user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
  	if @user.update(user_params)
  		redirect_to user_path(@user.id), notice:"successfully"
    else 
      flash[:notice] = "error"
      render action: :edit

    
  	end
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book)
    else
     
      @user = User.find(current_user.id)
      
      @books = Book.all
      render :index
    end
  end

  def destroy
  	book = Book.find(params[:id])
  	book.destroy
  	redirect_to books_path
  end

  private 
  def user_params
  	params.require(:user).permit(:name, :profile_image, :introduction)
  end 
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/about/show.html.erb
<div class='body'>
      <div class='container'>

        <p id="notice"></p>


      	<h1>Welcome to <span class='glyphicon glyphicon-book'></span><strong>Bookers</strong>!</h1>


      </div>
    </div>

    <footer>
  <div class='container'>
  	<div class='row'>
    	<div class='col-xs-3 col-xs-offset-9'>
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>

app/views/books/edit.html.erb
<h3>Editing Book</h3>
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>
<% if @book.errors.any? %>
				          <div id="error_explanation" class="alert alert-danger">
				            <ul>
				              <% @book.errors.full_messages.each do |message| %>
				                <li><%= message %></li>
				              <% end %>
				            </ul>
				          </div>
<% end %>
<%= form_for(@book) do |f| %>
	<h4>Title</h4>
	<%= f.text_field :title %>
	<h4>Opinion</h4>
	<%= f.text_area :body %>
    <%= f.submit 'Update Book' %>
	<%= link_to 'show',book_path(@book) %>
	<%= link_to 'back',books_path %>
<% end %>

app/views/books/index.html.erb
<div class="row">
	<% if flash[:notice] %>
	  <p><%= flash[:notice] %></p>
	<% end %>
	<% if @book.errors.any? %>
				          <div id="error_explanation" class="alert alert-danger">
				            <ul>
				              <% @book.errors.full_messages.each do |message| %>
				                <li><%= message %></li>
				              <% end %>
				            </ul>
				          </div>
    <% end %>

				<div class="col-xs-3">
					<h2>User info</h2>
					<table class="table table-hover table-inverse">
						<tr><%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img-circle pull-left profile-img", fallback:"no_image.jpg" %></tr> 
						<tr>
							<th>name</th>
							<th><%= @user.name %></th>
						</tr>
						<tr>
							<th>introduction</th>
							<th><%= @user.introduction %></th>
						</tr>
					</table>
					<div class="row">

						<<% if @user == current_user %>
						<%= link_to edit_user_path(@user) do %>
						<span class="col-xs-12 btn btn-defaut glyphicon glyphicon-asterisk" aria-hidden="true"></span>
						<% end %>
						<% else %>
						<%= link_to user_path(current_user.id) do %>
						<span class="col-xs-12 btn btn-defaut glyphicon glyphicon-asterisk" aria-hidden="true"></span>
						<% end %>
					
						<% end %>
					</div>
					<h2>New Book</h2>
					<%= form_for @book do |f| %>
						<h4>Title</h4>
						<%= f.text_field :title %>
						<h4>Body</h4>
						<%= f.text_area :body %>
						<%= f.submit 'Creat Book' %>
					<% end %>
				</div>
				<div class="col-xs-9">
					
					<h2>Books</h2>
					<table class="table table-hover table-inverse">
						<tr>
							<th></th>
							<th>Title</th>
							<th>Opinion</th>
						</tr>
						<tbody>
							<% @books.each do |book| %>
							<tr>
								<td><%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg', class: " pull-left ", fallback:"no_image.jpg", size:'40x40' %></td>
								<td><%= link_to book.title, book_path(book) %></td>
								<td><%=  book.body %></td>
							</tr>
							<% end %>
							<%= paginate @books, class: "paginate" %>
							
						</tbody>

					</table>
				</div>
</div>

app/views/books/show.html.erb
			<div class="row">
				
					
				<div class="col-xs-3">
					<% if flash[:notice] %>
					<p><%= flash[:notice] %></p>
	                <% end %>
					
					<h2>User info</h2>
					<table class="table">
						<tr><%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img-circle pull-left profile-img", fallback:"no_image.jpg" %></tr> 
						<tr>
							<th>name</th>
							<th><%= @user.name%></th>
						</tr>
						<tr>
							<th>introduction</th>
							<th><%= @user.introduction %></th>
						</tr>
					</table>
					<div class="row">
						<% if @user == current_user %>
						<%= link_to edit_user_path(@user) do %>
						<span class="col-xs-12 btn btn-defaut glyphicon glyphicon-asterisk" aria-hidden="true"></span>
						<% end %>
						<% else %>
						<%= link_to user_path(current_user.id) do %>
						<span class="col-xs-12 btn btn-defaut glyphicon glyphicon-asterisk" aria-hidden="true"></span>
						<% end %>
					
						<% end %>
					</div>
					<h2>New Book</h2>
					<%= form_for(@book) do |f| %>
					<h4>Title</h4>
					<%= f.text_field :title %>
					<h4>Body</h4>
					<%= f.text_area :body %>
					<%= f.submit 'Creat Book' %>
					<% end %>
				</div>
				<div class="col-xs-9">
					
					<h2>Book detail</h2>
					<table class="table table-hover table-inverse">
						<tr>
						</tr>
						<tbody>
							
							<tr>
								<td><%= link_to user_path(@user) do %>
									<%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback:"no_image.jpg", size:'40x40' %>
									<br>
									<%= @user.name %>
									<% end %>
								</td>
									
								<td><%= link_to @booker.title, book_path(@booker) %></td>
								<td><%= @booker.body %></td>
								<% if @booker.user == current_user %>
								<td><%= link_to 'Edit', edit_book_path(@booker) %></td>
								<td><%= link_to 'Destroy',book_path(@booker), method: :delete, data: {confirm: '削除しますか？'} %></td>
								<% end %>

							</tr>


							
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!-- <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %> -->
   
    <title>Meshiterro</title>
    
  </head> 

  <body>

    <div class="header" id="header">
      <nav class="navbar navbar-main navbar-shadow" role="navigation" id="slide-nav">
        <div class="container relative">

          <div class="navbar-header">
            <a class="navbar-logo" href="/">
              Bookers
            </a>

   
           
          </div>
          <div id="slidemenu">
            <ul class="nav navbar-nav navbar-right" data-hover="dropdown" data-animations="zoomIn fadeIn fadeInUp fadeIn">
              <% if user_signed_in? %>
              <li class="">
                <%= link_to "Home", user_path(current_user.id), class:"glyphicon glyphicon-plus"  %>
              </li>
              <li class="">
                <%= link_to "Users", users_path, class: "glyphicon glyphicon-plus" %>
              </li>
              <li class="">
                <%= link_to "Books", books_path, class:"glyphicon glyphicon-minus" %>
              </li>
              <li class="">
                <%= link_to "logout", destroy_user_session_path, method: :delete %>
              </li>
              <% else %>
              <li class="">
                <%= link_to "Home", root_path, class:"glyphicon glyphicon-plus" %>
              </li>
              <li class="">
                <%= link_to "About", '/home/about' %>
              </li>
              <li class="">
                <%= link_to "sign up", new_user_registration_path,class: "glyphicon glyphicon-home home" %>
              </li>
              <li class="">
                <%= link_to "login", edit_user_registration_path %>
              </li>
              <% end %> 

            </ul>
          </div>
        </div>
      </nav>
    </div>
      
    <%= yield %>
    </body>
   

app/views/root/top.html.erb
  <div class='body'>
      <div class='container'>
        <p id="notice">Signed out successfully.</p>

        <p id="notice"></p>


        <div class="row">
          <div class='top-message col-md-offset-3 col-md-6'>
            <h1>welcome to <span class='glyphicon glyphicon-minus'><strong>Bookers</strong>  !!</span></h1>
                  <p>In  <span class='glyphicon glyphicon-plus'></span><strong>Bookers</strong>, </p>
                  <p>you can share and exchange  your opinions , inpressions , and emotions</p>
                  <p> about varioius books!</p>

            <div class="btn-wrapper">
              <div class="row">
                 <p><a class="btn btn-info col-xs-10 col-xs-offset-1 sign_in" href="/users/sign_in">Log in</a></p>
              </div>
              <div class="row">
                <p><a class="btn btn-success col-xs-10 col-xs-offset-1 sign_up" href="/users/sign_up">Sign Up</a></p>
              </div>
            </div>
          </div>
        </div>

  </div>
        

    <footer>
      <div class='container'>
        <div class='row'>
          <div class='col-xs-3 col-xs-offset-9'>
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>

app/views/users/edit.html.erb
<div class="body-wrap">
  <div id="st-container" class="st-container">
    <div class="st-pusher">
      <div class="st-content">
        <div class="st-content-inner">      
          <section class="slice slice-lg sct-color-1">
              <div class="container">
               
                <% if flash[:notice] %>
                <p><%= flash[:notice] %></p>
                <% end %>
                <% if @user.errors.any? %>
                  <div id="error_explanation" class="alert alert-danger">
                    <ul>
                      <% @user.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                      <% end %>
                    </ul>
                  </div>
                <% end %>
                  <div class="row">
                      <div class="col-md-4 col-md-offset-4">
                          <div class="form-user style-1 rounded has-shadow-1"> 
                            <div class="form-header text-center">
                                <h2 class="form-header-title">プロフィール編集</h2>
                            </div>
                            <div class="form-body">
                              <%= form_for(@user) do |f| %>
                              <div class="form-group has-icon">
                                <label for="user_name">Name</label>
                                <%= f.text_field :name, autofocus: true, class:"form-control", id:"inputUsername", placeholder:"名前" %>
                                <span class="class="fa fa-user form-control-icon" aria-hidden="true"></span>
                              </div>
                              <div class="form-group has-icon">
                                <div class="user-edit-image">
                                <%= attachment_image_tag @user, :profile_image, :fil, 60, 60, class:"img-circle pull-left profile-thumb", fallback: "no_image.jpg"%>
                                </div>
                              <label for="user_name">ProfileImage</label>
                              <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class:"user-edit-form" %>
                              </div>
                              <label for="user_name">Introduction</label>
                              <%= f.text_field :introduction, class:"user-edit-form" %>

                              <%= f.submit "変更保存", class:"btn btn-lg btn-block btn-base-1 mt-20" %>
                              <% end %>
                            </div>
                          </div> 
                      </div>
                  </div>
              </div>
          </section>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="row">
	     
         <% if @book.errors.any? %>
          <div id="error_explanation" class="alert alert-danger">
            <ul>
              <% @book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
         <% end %>
         
				<div class="col-xs-3">
					<h2>User info</h2>
					<table class="table table-hover table-inverse">
						<tr><%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img-circle pull-left profile-img", fallback:"no_image.jpg" %></tr> 
						<tr>
							<th>name</th>
							<th><%= current_user.name %></th>
						</tr>
						<tr>
							<th>introduction</th>
							<th><%= current_user.introduction %></th>
						</tr>
					</table>
					<div class="row">
						<% if @user == current_user %>
						<%= link_to edit_user_path(@user) do %>
						<span class="col-xs-12 btn btn-defaut glyphicon glyphicon-asterisk" aria-hidden="true"></span>
						<% end %>
						<% else %>
						<%= link_to user_path(current_user.id) do %>
						<span class="col-xs-12 btn btn-defaut glyphicon glyphicon-asterisk" aria-hidden="true"></span>
						<% end %>
					
						<% end %>
					</div>
					<h2>New Book</h2>
					<%= form_for @book do |f| %>
						<h4>Title</h4>
						<%= f.text_field :title %>
						<h4>Body</h4>
						<%= f.text_area :body %>
						<%= f.submit 'Creat Book' %>
					<% end %>
				</div>
				<div class="col-xs-9">
					<% if flash[:notice] %>
					<p><%= flash[:notice] %></p>
					<% end %>
					<h2>Users</h2>
					<table class="table table-hover table-inverse">
						<tr>
							
							<th>image</th>
							<th>name</th>
							<th></th>
						</tr>
						<tbody>
							<% @users.each do |user| %>
							<tr>
								<td><%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', class: " pull-left ", fallback:"no_image.jpg", size:'40x40'%></td>
								
								<td><%=  user.name %></td>
								<td><%= link_to "show", user_path(user)%></td>
							</tr>
							
							<% end %>
							
						</tbody>
					</table>
				</div>
</div>

app/views/users/show.html.erb
	

	<div class="body">
		<div class="container">
			<% if flash[:notice] %>
			  <p><%= flash[:notice] %></p>
			<% end %>
						
	        
	        

			<div class="row">
				<% if @book.errors.any? %>
		          <div id="error_explanation" class="alert alert-danger">
		            <ul>
		              <% @book.errors.full_messages.each do |message| %>
		                <li><%= message %></li>
		              <% end %>
		            </ul>
		          </div>
		         <% end %>
				<div class="col-xs-3">
					<h2>User info</h2>
					<table class="table table-hover table-inverse">

						<tr><%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img-circle pull-left profile-img", fallback:"no_image.jpg" %></tr> 
						<tr>
							<th>name</th>
							<th><%= @user.name %></th>
						</tr>
						<tr>
							<th>introduction</th>
							<th><%= @user.introduction %></th>
						</tr>
					</table>
					<div class="row">
						<% if @user == current_user %>
						<%= link_to edit_user_path(@user) do %>
						<span class="col-xs-12 btn btn-defaut glyphicon glyphicon-asterisk" aria-hidden="true"></span>
						<% end %>
						<% else %>
						<%= link_to user_path(current_user.id) do %>
						<span class="col-xs-12 btn btn-defaut glyphicon glyphicon-asterisk" aria-hidden="true"></span>
						<% end %>
					
						<% end %>
					</div>
					<h2>New Book</h2>
					<%= form_for @book do |f| %>
						<h4>Title</h4>
						<%= f.text_field :title %>
						<h4>Body</h4>
						<%= f.text_area :body %>
						<%= f.submit 'Creat Book' %>
					<% end %>
				</div>
				<div class="col-xs-9">
					<% if flash[:notice] %>
					<p><%= flash[:notice] %></p>
					<% end %>
					<h2>Books</h2>
					<table class="table table-hover table-inverse">
						<tr><th></th>
							<th>Title</th>
							<th>Opinion</th>
						</tr>
						<tbody>
							<% @post_images.each do |book| %>

							<tr>
								<td><%= attachment_image_tag @user, :profile_image, :fill, 20, 20, format: 'jpeg', class: "pull-left", fallback:"no_image.jpg",size:'40x40'  %></td> 
						
								<td><%= link_to book.title, book_path(book.id) %></td>
								<td><%=  book.body %></td>
							</tr>
							<% end %>
							<%= paginate @post_images, class: "paginate" %>

							
						</tbody>

					</table>
				</div>
			</div>
		</div>
	</div>